server :
  port: 8080
spring:
  application.name: ewm-service
  spring:
    jpa:
      hibernate:
        ddl-auto=create-drop:
  main.banner-mode: OFF
  sql:
    init:
      mode: always
  jpa:
    hibernate:

      ddl-auto: none
    show-sql: true
  datasource:
    username: user2
    password: 678910
    url: jdbc:postgresql://localhost:6541/postgres2
    driver-class-name: org.postgresql.Driver

    logging:
      level:
        org.springframework.orm:
          jpa: INFO
          transactiont: INFO
          JpaTransactionManager: DEBUG