services:
  stats-server:
    build:
      context: ./stats/stats-server
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=12345

  stats-db:
    image: postgres:16.1
    container_name: ewm-stat-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=12345
    
  ewm-service:
    build: ./ewm-service
    ports:
      - "8080:8080"
    environment:
      - STATS_SERVER_URL=http://stats-service:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/postgres2
      - SPRING.DATASOURCE.USERNAME=user2
      - SPRING.DATASOURCE.PASSWORD=678910

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=postgres2
      - POSTGRES_USER=user2
      - POSTGRES_PASSWORD=678910
