services:
  stats-server:
    build:
      context: ./stats/stats-server
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=12345

  stats-db:
    image: postgres:16.1
    container_name: ewm-stat-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=user
      - POSTGRES_DB=postgres

  ewm-service:
    build: ./ewm-service
    ports:
      - "8080:8080"