server :
  port: 9090
spring:
  application.name: stats-server
  main.banner-mode: OFF
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    username: user
    password: 12345
    url: jdbc:postgresql://localhost:6542/postgres
    driver-class-name: org.postgresql.Driver